<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="System.IO.Pipelines" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Generators/BaSL.SourceGenerators/BaSL.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
