<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" PrivateAssets="all" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="BaSL" HintPath="../../BaSL/bin/$(Configuration)/netstandard2.1/BaSL.dll" />
        <ProjectReference Include="../BaSL.SourceGenerators/BaSL.SourceGenerators.csproj" />
    </ItemGroup>

</Project>