<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit" Version="1.1.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../BaSL.SourceGenerators/BaSL.SourceGenerators.csproj" />
    </ItemGroup>

</Project>