<Project>

    <PropertyGroup>
        <LangVersion>14</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <PropertyGroup>
        <Authors>Axwabo</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

</Project>